import { useState, useEffect, useCallback } from 'react';
import { FileText, Download, Calendar, Filter, Terminal, Trash2, Eye, Search, ChevronLeft, ChevronRight, BarChart3, Shield, AlertTriangle, X } from 'lucide-react';
import { Button } from '../ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';
import { Badge } from '../ui/badge';
import { ScrollArea } from '../ui/scroll-area';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../ui/tabs';
import { getSystemLogs, getReports, generateReport, getReportDetail, deleteReport } from '../../services/api';
import { downloadCSV } from '../../utils/export';
import { toast } from 'sonner';

export function ReportsLogs() {
  // ── Reports state ──
  const [reports, setReports] = useState<any[]>([]);
  const [selectedReport, setSelectedReport] = useState<any>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [reportPeriod, setReportPeriod] = useState('daily');
  const [customStartDate, setCustomStartDate] = useState('');
  const [customEndDate, setCustomEndDate] = useState('');

  // ── Logs state ──
  const [logs, setLogs] = useState<any[]>([]);
  const [logsTotal, setLogsTotal] = useState(0);
  const [logsPage, setLogsPage] = useState(1);
  const [logsLimit] = useState(50);
  const [logLevel, setLogLevel] = useState('all-levels');
  const [logSource, setLogSource] = useState('all-sources');
  const [logSearch, setLogSearch] = useState('');
  const [logSearchInput, setLogSearchInput] = useState('');

  // ── Fetch functions ──
  const fetchReports = useCallback(() => {
    getReports().then(setReports).catch(console.error);
  }, []);

  const fetchLogs = useCallback(() => {
    getSystemLogs(logsPage, logsLimit, logLevel, logSource, logSearch)
      .then(res => {
        if (res) {
          const mapped = (res.data || []).map((l: any) => ({
            timestamp: l.timestamp,
            level: l.level || l.details?.action || 'INFO',
            source: l.source || l.event_type || 'System',
            message: l.message || (l.details ? `${l.details.action} → ${l.details.source_ip} (conf: ${(l.details.confidence * 100).toFixed(1)}%)` : 'System event'),
          }));
          setLogs(mapped);
          setLogsTotal(res.total_records || 0);
        }
      })
      .catch(console.error);
  }, [logsPage, logsLimit, logLevel, logSource, logSearch]);

  useEffect(() => { fetchReports(); }, []);
  useEffect(() => { fetchLogs(); }, [fetchLogs]);

  // ── Handlers ──
  const handleGenerate = async () => {
    setIsGenerating(true);
    try {
      const report = await generateReport(
        reportPeriod,
        reportPeriod === 'custom' ? customStartDate : undefined,
        reportPeriod === 'custom' ? customEndDate : undefined
      );
      toast.success(`Report ${report.report_id} generated successfully!`);
      fetchReports();
    } catch {
      toast.error('Failed to generate report');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleViewReport = async (reportId: string) => {
    try {
      const detail = await getReportDetail(reportId);
      setSelectedReport(detail);
    } catch {
      toast.error('Failed to load report details');
    }
  };

  const handleDeleteReport = async (reportId: string) => {
    if (!confirm(`Delete report ${reportId}? This cannot be undone.`)) return;
    try {
      await deleteReport(reportId);
      toast.success('Report deleted');
      if (selectedReport?.report_id === reportId) setSelectedReport(null);
      fetchReports();
    } catch {
      toast.error('Failed to delete report');
    }
  };

  const handleExportReport = (report: any) => {
    const exportData = [
      { field: 'Report ID', value: report.report_id },
      { field: 'Title', value: report.title },
      { field: 'Generated', value: report.generated_at },
      { field: 'Generated By', value: report.generated_by },
      { field: 'Total Detections', value: report.summary?.total_detections },
      { field: 'Total Blocks', value: report.summary?.total_blocks },
      { field: 'Total Alerts', value: report.summary?.total_alerts },
      { field: 'Active Alerts', value: report.summary?.active_alerts },
      { field: 'Total Logs', value: report.summary?.total_logs },
    ];
    if (report.top_attack_sources) {
      report.top_attack_sources.forEach((s: any, i: number) => {
        exportData.push({ field: `Top Source #${i + 1}`, value: `${s.ip} (${s.count} attacks)` });
      });
    }
    downloadCSV(exportData, `${report.report_id}.csv`);
    toast.success(`Exported ${report.report_id} as CSV`);
  };

  const handleLogSearch = () => {
    setLogSearch(logSearchInput);
    setLogsPage(1);
  };

  const totalPages = Math.max(1, Math.ceil(logsTotal / logsLimit));

  return (
    <div className="p-8 max-w-[1400px] mx-auto">
      <div className="flex items-center justify-between mb-8">
        <h2 className="text-[#E6EDF3]">Reports & Logs</h2>
        <div className="flex items-center gap-3">
          <Select value={reportPeriod} onValueChange={setReportPeriod}>
            <SelectTrigger className="w-[160px] bg-[#0D1117] border-[#30363D] text-[#E6EDF3]">
              <Calendar className="w-4 h-4 mr-2" />
              <SelectValue />
            </SelectTrigger>
            <SelectContent className="bg-[#161B22] border-[#30363D]">
              <SelectItem value="daily" className="text-[#E6EDF3]">Daily Report</SelectItem>
              <SelectItem value="weekly" className="text-[#E6EDF3]">Weekly Report</SelectItem>
              <SelectItem value="monthly" className="text-[#E6EDF3]">Monthly Report</SelectItem>
              <SelectItem value="custom" className="text-[#E6EDF3]">Custom Timeframe</SelectItem>
              <SelectItem value="all" className="text-[#E6EDF3]">All Time</SelectItem>
            </SelectContent>
          </Select>

          {reportPeriod === 'custom' && (
            <div className="flex items-center gap-2">
              <input
                type="date"
                value={customStartDate}
                onChange={(e) => setCustomStartDate(e.target.value)}
                className="bg-[#0D1117] border border-[#30363D] text-[#E6EDF3] text-sm rounded-md px-3 py-2 outline-none focus:border-[#1F6FEB] [color-scheme:dark]"
              />
              <span className="text-[#7D8590]">to</span>
              <input
                type="date"
                value={customEndDate}
                onChange={(e) => setCustomEndDate(e.target.value)}
                className="bg-[#0D1117] border border-[#30363D] text-[#E6EDF3] text-sm rounded-md px-3 py-2 outline-none focus:border-[#1F6FEB] [color-scheme:dark]"
              />
            </div>
          )}

          <Button
            className="bg-[#1F6FEB] hover:bg-[#1F6FEB]/90 gap-2"
            disabled={isGenerating}
            onClick={handleGenerate}
          >
            <FileText className="w-4 h-4" />
            {isGenerating ? 'Generating...' : 'Generate Report'}
          </Button>
        </div>
      </div>

      <Tabs defaultValue="reports" className="space-y-6">
        <TabsList className="bg-[#1E232B] border border-[#30363D]">
          <TabsTrigger value="reports" className="data-[state=active]:bg-[#1F6FEB] data-[state=active]:text-white">
            Reports ({reports.length})
          </TabsTrigger>
          <TabsTrigger value="logs" className="data-[state=active]:bg-[#1F6FEB] data-[state=active]:text-white">
            System Logs ({logsTotal.toLocaleString()})
          </TabsTrigger>
        </TabsList>

        {/* ── Reports Tab ── */}
        <TabsContent value="reports" className="space-y-6">
          {reports.length === 0 ? (
            <div className="bg-[#1E232B] rounded-2xl p-12 border border-[#30363D] text-center">
              <FileText className="w-10 h-10 text-[#7D8590] mx-auto mb-3" />
              <p className="text-[#7D8590]">No reports generated yet.</p>
              <p className="text-[#7D8590] text-sm mt-1">Click "Generate Report" to create your first security report from live data.</p>
            </div>
          ) : (
            <div className="space-y-4">
              {reports.map((report: any) => (
                <div key={report.report_id} className="bg-[#1E232B] border border-[#30363D] rounded-2xl p-5 hover:border-[#1F6FEB]/50 transition-colors">
                  <div className="flex items-start justify-between mb-3">
                    <div className="flex-1">
                      <div className="flex items-center gap-3 mb-2">
                        <h4 className="text-[#E6EDF3]">{report.title}</h4>
                        <Badge variant="outline" className="border-[#58A6FF] text-[#58A6FF]">
                          {report.type}
                        </Badge>
                        {report.period_type && (
                          <Badge variant="outline" className={
                            report.period_type === 'monthly' ? 'border-[#BC8CFF] text-[#BC8CFF]' :
                              report.period_type === 'weekly' ? 'border-[#3FB950] text-[#3FB950]' :
                                report.period_type === 'all' ? 'border-[#FFA657] text-[#FFA657]' :
                                  report.period_type === 'custom' ? 'border-[#58A6FF] text-[#58A6FF]' :
                                    'border-[#7D8590] text-[#7D8590]'
                          }>
                            {report.period_type.charAt(0).toUpperCase() + report.period_type.slice(1)}
                          </Badge>
                        )}
                      </div>
                      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
                        <div>
                          <span className="text-[#7D8590]">Report ID: </span>
                          <span className="text-[#E6EDF3] font-mono">{report.report_id}</span>
                        </div>
                        <div>
                          <span className="text-[#7D8590]">Generated: </span>
                          <span className="text-[#E6EDF3]">{report.generated_at}</span>
                        </div>
                        <div>
                          <span className="text-[#7D8590]">By: </span>
                          <span className="text-[#E6EDF3]">{report.generated_by || 'system'}</span>
                        </div>
                        <div>
                          <span className="text-[#7D8590]">Period: </span>
                          <span className="text-[#E6EDF3]">{report.period}</span>
                        </div>
                        <div>
                          <span className="text-[#7D8590]">Detections: </span>
                          <span className="text-[#E6EDF3] font-mono">{(report.summary?.total_detections || 0).toLocaleString()}</span>
                        </div>
                      </div>
                    </div>
                    <div className="flex gap-2 ml-4">
                      <Button variant="outline" size="sm" className="border-[#30363D] text-[#E6EDF3] gap-1" onClick={() => handleViewReport(report.report_id)}>
                        <Eye className="w-3 h-3" /> View
                      </Button>
                      <Button variant="outline" size="sm" className="border-[#30363D] text-[#E6EDF3] gap-1" onClick={() => handleExportReport(report)}>
                        <Download className="w-3 h-3" /> CSV
                      </Button>
                      <Button variant="outline" size="sm" className="border-[#FF4D4D]/30 text-[#FF4D4D] gap-1 hover:bg-[#FF4D4D]/10" onClick={() => handleDeleteReport(report.report_id)}>
                        <Trash2 className="w-3 h-3" />
                      </Button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* ── Report Detail Panel ── */}
          {selectedReport && (
            <div className="bg-[#1E232B] rounded-2xl p-6 border border-[#1F6FEB]/40">
              <div className="flex items-center justify-between mb-6">
                <h3 className="text-[#E6EDF3]">
                  {selectedReport.title}
                  <span className="text-[#7D8590] text-sm ml-2">({selectedReport.report_id})</span>
                </h3>
                <Button variant="outline" size="sm" className="border-[#30363D] text-[#E6EDF3]" onClick={() => setSelectedReport(null)}>
                  <X className="w-4 h-4" />
                </Button>
              </div>

              {/* Summary Stats */}
              <div className="grid grid-cols-2 md:grid-cols-5 gap-4 mb-6">
                {[
                  { label: 'Total Detections', value: selectedReport.summary?.total_detections, color: '#58A6FF', icon: Shield },
                  { label: 'IP Blocks', value: selectedReport.summary?.total_blocks, color: '#FF4D4D', icon: Shield },
                  { label: 'Total Alerts', value: selectedReport.summary?.total_alerts, color: '#FFA657', icon: AlertTriangle },
                  { label: 'Active Alerts', value: selectedReport.summary?.active_alerts, color: '#D29922', icon: AlertTriangle },
                  { label: 'Log Entries', value: selectedReport.summary?.total_logs, color: '#3FB950', icon: BarChart3 },
                ].map((stat, i) => (
                  <div key={i} className="bg-[#0D1117] rounded-xl p-4 border border-[#30363D]">
                    <div className="flex items-center gap-2 mb-2">
                      <stat.icon className="w-4 h-4" style={{ color: stat.color }} />
                      <span className="text-[#7D8590] text-xs">{stat.label}</span>
                    </div>
                    <div className="text-2xl font-bold font-mono" style={{ color: stat.color }}>
                      {(stat.value || 0).toLocaleString()}
                    </div>
                  </div>
                ))}
              </div>

              {/* Top Attack Sources & Action Distribution */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <h4 className="text-[#E6EDF3] text-sm mb-3">Top Attack Sources</h4>
                  {selectedReport.top_attack_sources?.length > 0 ? (
                    <div className="space-y-2">
                      {selectedReport.top_attack_sources.map((s: any, i: number) => (
                        <div key={i} className="flex items-center justify-between bg-[#0D1117] rounded-lg px-4 py-2.5 border border-[#30363D]">
                          <span className="text-[#E6EDF3] font-mono text-sm">{s.ip}</span>
                          <Badge variant="outline" className="border-[#FF4D4D] text-[#FF4D4D]">{s.count} attacks</Badge>
                        </div>
                      ))}
                    </div>
                  ) : (
                    <p className="text-[#7D8590] text-sm">No attack sources found.</p>
                  )}
                </div>
                <div>
                  <h4 className="text-[#E6EDF3] text-sm mb-3">Action Distribution</h4>
                  {selectedReport.action_distribution?.length > 0 ? (
                    <div className="space-y-2">
                      {selectedReport.action_distribution.map((a: any, i: number) => {
                        const total = selectedReport.summary?.total_detections || 1;
                        const pct = ((a.count / total) * 100).toFixed(1);
                        const color = a.action === 'CRITICAL_BLOCK' ? '#FF4D4D' : a.action === 'BLOCK_IP' ? '#FFA657' : a.action === 'ALERT_ADMIN' ? '#D29922' : '#3FB950';
                        return (
                          <div key={i} className="bg-[#0D1117] rounded-lg px-4 py-2.5 border border-[#30363D]">
                            <div className="flex items-center justify-between mb-1">
                              <span className="text-[#E6EDF3] text-sm">{a.action}</span>
                              <span className="text-[#7D8590] text-xs">{a.count} ({pct}%)</span>
                            </div>
                            <div className="h-1.5 bg-[#30363D] rounded-full overflow-hidden">
                              <div className="h-full rounded-full" style={{ width: `${pct}%`, backgroundColor: color }} />
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  ) : (
                    <p className="text-[#7D8590] text-sm">No action data available.</p>
                  )}
                </div>
              </div>

              <div className="mt-4 text-[#7D8590] text-xs">
                Generated by <span className="text-[#E6EDF3]">{selectedReport.generated_by}</span> on {selectedReport.generated_at}
              </div>
            </div>
          )}
        </TabsContent>

        {/* ── System Logs Tab ── */}
        <TabsContent value="logs" className="space-y-6">
          <div className="bg-[#1E232B] rounded-2xl p-6 border border-[#30363D]">
            <div className="flex flex-col md:flex-row gap-4 mb-6">
              <Select value={logLevel} onValueChange={(v) => { setLogLevel(v); setLogsPage(1); }}>
                <SelectTrigger className="w-full md:w-[180px] bg-[#0D1117] border-[#30363D] text-[#E6EDF3]">
                  <Filter className="w-4 h-4 mr-2" />
                  <SelectValue />
                </SelectTrigger>
                <SelectContent className="bg-[#161B22] border-[#30363D]">
                  <SelectItem value="all-levels" className="text-[#E6EDF3]">All Levels</SelectItem>
                  <SelectItem value="critical" className="text-[#E6EDF3]">Critical</SelectItem>
                  <SelectItem value="high" className="text-[#E6EDF3]">High</SelectItem>
                  <SelectItem value="medium" className="text-[#E6EDF3]">Medium</SelectItem>
                  <SelectItem value="info" className="text-[#E6EDF3]">Info</SelectItem>
                </SelectContent>
              </Select>

              <Select value={logSource} onValueChange={(v) => { setLogSource(v); setLogsPage(1); }}>
                <SelectTrigger className="w-full md:w-[180px] bg-[#0D1117] border-[#30363D] text-[#E6EDF3]">
                  <Terminal className="w-4 h-4 mr-2" />
                  <SelectValue />
                </SelectTrigger>
                <SelectContent className="bg-[#161B22] border-[#30363D]">
                  <SelectItem value="all-sources" className="text-[#E6EDF3]">All Sources</SelectItem>
                  <SelectItem value="IDS_RESPONSE" className="text-[#E6EDF3]">IDS Response</SelectItem>
                  <SelectItem value="SYSTEM" className="text-[#E6EDF3]">System</SelectItem>
                  <SelectItem value="AUTH" className="text-[#E6EDF3]">Auth</SelectItem>
                </SelectContent>
              </Select>

              {/* Search */}
              <div className="flex gap-2 flex-1">
                <div className="relative flex-1">
                  <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-[#7D8590]" />
                  <input
                    value={logSearchInput}
                    onChange={e => setLogSearchInput(e.target.value)}
                    onKeyDown={e => e.key === 'Enter' && handleLogSearch()}
                    placeholder="Search logs..."
                    className="w-full bg-[#0D1117] border border-[#30363D] rounded-lg pl-10 pr-4 py-2 text-[#E6EDF3] text-sm focus:outline-none focus:border-[#1F6FEB] placeholder:text-[#484F58]"
                  />
                </div>
                {logSearch && (
                  <Button variant="outline" size="sm" className="border-[#30363D] text-[#7D8590]" onClick={() => { setLogSearch(''); setLogSearchInput(''); setLogsPage(1); }}>
                    <X className="w-4 h-4" />
                  </Button>
                )}
              </div>

              <Button
                variant="outline"
                className="border-[#30363D] text-[#E6EDF3] gap-2"
                onClick={() => { downloadCSV(logs, 'system-logs.csv'); toast.success('Logs exported as CSV'); }}
              >
                <Download className="w-4 h-4" />
                Export
              </Button>
            </div>

            <ScrollArea className="h-[500px] bg-[#0D1117] rounded-lg border border-[#30363D] p-4">
              <div className="space-y-1 font-mono text-sm">
                {logs.length > 0 ? logs.map((log: any, index: number) => (
                  <div
                    key={index}
                    className="flex gap-3 py-2 px-3 hover:bg-[#161B22] rounded transition-colors"
                  >
                    <span className="text-[#7D8590] whitespace-nowrap min-w-[150px]">{log.timestamp}</span>
                    <Badge
                      variant="outline"
                      className={`whitespace-nowrap min-w-[70px] justify-center ${log.level === 'CRITICAL' || log.level === 'CRITICAL_BLOCK'
                        ? 'border-[#FF4D4D] text-[#FF4D4D]'
                        : log.level === 'HIGH' || log.level === 'BLOCK_IP'
                          ? 'border-[#FFA657] text-[#FFA657]'
                          : log.level === 'MEDIUM' || log.level === 'ALERT_ADMIN'
                            ? 'border-[#D29922] text-[#D29922]'
                            : log.level === 'LOW' || log.level === 'LOG_ONLY'
                              ? 'border-[#7D8590] text-[#7D8590]'
                              : 'border-[#3FB950] text-[#3FB950]'
                        }`}
                    >
                      {log.level}
                    </Badge>
                    <span className="text-[#58A6FF] whitespace-nowrap">[{log.source}]</span>
                    <span className="text-[#C9D1D9] truncate">{log.message}</span>
                  </div>
                )) : (
                  <div className="text-center py-12 text-[#7D8590]">
                    <Terminal className="w-8 h-8 mx-auto mb-2 opacity-50" />
                    <p className="text-sm">No log entries found{logSearch ? ` matching "${logSearch}"` : ''}.</p>
                    <p className="text-xs mt-1">Run the traffic simulator to generate log data.</p>
                  </div>
                )}
              </div>
            </ScrollArea>

            {/* Pagination */}
            <div className="flex items-center justify-between mt-4 pt-4 border-t border-[#30363D]">
              <span className="text-[#7D8590] text-sm">
                Showing {Math.min((logsPage - 1) * logsLimit + 1, logsTotal)}–{Math.min(logsPage * logsLimit, logsTotal)} of {logsTotal.toLocaleString()} entries
              </span>
              <div className="flex items-center gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  className="border-[#30363D] text-[#E6EDF3]"
                  disabled={logsPage <= 1}
                  onClick={() => setLogsPage(p => p - 1)}
                >
                  <ChevronLeft className="w-4 h-4" />
                </Button>
                <span className="text-[#E6EDF3] text-sm px-2">Page {logsPage} of {totalPages}</span>
                <Button
                  variant="outline"
                  size="sm"
                  className="border-[#30363D] text-[#E6EDF3]"
                  disabled={logsPage >= totalPages}
                  onClick={() => setLogsPage(p => p + 1)}
                >
                  <ChevronRight className="w-4 h-4" />
                </Button>
              </div>
            </div>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}
